### ISSUE TITLE
Software review notes

### ISSUE THREAD

**Issue by cgostic** [UBC-MDS/laundRy#65]
### Categorize @cgostic 

- [x] **FUNCTION:** truncate long lines (80 char) in **test** and **function**
- [x] **DOCUMENTATION:** Change the phrase "sub vectors" to just "character vectors". 
    - I think this appears in categorize and fill_missing, maybe others?
- [x] **DOCUMENTATION:** Comma + space between items in vectors in examples
- [x] **DOCUMENTATION:** Add clarity on what will be classified as categorical vs. numeric.

### Column transformer @arunmarria 

- [x] **FUNCTION:** issue with column transformation for mtcars dataset --> https://github.com/UBC-MDS/software-review/issues/19
- [ ] **FUNCTION:** truncate long lines (80 char) in **test** and **function**
- [x] **DOCUMENTATION:** specify vector names in column list
    - "For the argument column_list, it would help to know what names the user needs to include in the list, like list(name1 = c(blah, blah), name2 = c(blah, blah))."
- [x] **DOCUMENTATION:** Mention other possibilities for scaling options in documentation (i.e. what can be passed into num_trans?)
- [x] **DOCUMENTATION:** Add example
- [x] **DOCUMENTATION:** Write `value` output as a sentence
    - e.g. "A list with named items x_train and x_list that have been transformed according to the arguments specified"

### Feature selection @amank90 

- [x] **FUNCTION**: Return type is not a list, but a factor vector. Either update docs, or update output.
- [x] **FUNCTION:** 1 Error noted -- https://github.com/UBC-MDS/software-review/issues/19
- [x] **FUNCTION:** unexpected behavior with input n_features > number of columns --https://github.com/UBC-MDS/software-review/issues/19
- [ ] **FUNCTION:** truncate long lines (80 char) in **test** and **function**
- [x] **DOCUMENTATION:** typo "rensponse"
- [x] **DOCUMENTATION:** the description...what method does this function actually use? --> https://github.com/UBC-MDS/software-review/issues/19
- [x] **DOCUMENTATION:**  for description of mode, consider "a string, either "regression" or "classification"".
- [x] **DOCUMENTATION:** Describe what "n_features" is beyond it's type
- [x] **DOCUMENTATION:** Describe return value beyond it's type
- [x] **FUNCTION:** Adding default value for "n_features"

### Fill missing @zanderhinton 

- [x] **DOCUMENTATION:** Change the phrase "sub vectors" to just "character vectors". 
    - I think this appears in categorize and fill_missing, maybe others?
- [x] **DOCUMENTATION:** describe return value  -- names of items in list being returned 
- [x] **FUNCTION:** truncate long lines (80 char) in **test** and **function**

### Tests @cgostic 

- [x] <- instead of =

### Other @cgostic 

- [x] List all authors in description
